### ISSUE TITLE
Faulty ECS server with Ansible

### ISSUE THREAD

**Issue by wuebbels** [opentelekomcloud/ansible-collection-cloud#173]
Creating an ECS server with the recent Ansible (4.10.0) and OpenstackSDK (0.61.0) results in a "Faulty" ECS server.
Here the complete output of the Ansible task:
```
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": {"data": {"server": {"OS-DCF:diskConfig": "MANUAL", "OS-EXT-AZ:availability_zone": "eu-de-01", "OS-EXT-SRV-ATTR:host": "878bbc505aea6b7ee410bef50cb622e603e8fd351d48dc3fc98575f7", "OS-EXT-SRV-ATTR:hostname": "testhost", "OS-EXT-SRV-ATTR:hypervisor_hostname": "ac8ff6a8e9d01e1aa5cd26b49ebaa128131c87fde9db0622dbadfad8", "OS-EXT-SRV-ATTR:instance_name": "instance-010d18ca", "OS-EXT-SRV-ATTR:kernel_id": "", "OS-EXT-SRV-ATTR:launch_index": 0, "OS-EXT-SRV-ATTR:ramdisk_id": "", "OS-EXT-SRV-ATTR:reservation_id": "r-qkyu60xj", "OS-EXT-SRV-ATTR:root_device_name": "/dev/vda", "OS-EXT-SRV-ATTR:user_data": null, "OS-EXT-STS:power_state": 0, "OS-EXT-STS:task_state": null, "OS-EXT-STS:vm_state": "error", "OS-SCH-HNT:scheduler_hints": null, "OS-SRV-USG:launched_at": null, "OS-SRV-USG:terminated_at": null, "accessIPv4": "", "accessIPv6": "", "addresses": {}, "adminPass": null, "az": "eu-de-01", "block_device_mapping": null, "cloud": "repository-dev", "config_drive": "", "created": "2022-02-02T13:26:31Z", "created_at": "2022-02-02T13:26:31Z", "description": "testhost", "disk_config": "MANUAL", "flavor": {"disk": 0, "ephemeral": 0, "extra_specs": {"cond:compute": "autorecovery", "cond:image": "__support_kvm=true", "cond:operation:az": "eu-de-01(normal),eu-de-02(normal),eu-de-03(normal)", "cond:operation:status": "abandon", "ecs:generation": "s6", "ecs:performancetype": "normal", "ecs:virtualization_env_types": "CloudCompute", "hw:cpu_cores": "1", "hw:cpu_sockets": "1", "hw:cpu_threads": "1", "hw:mem_page_size": "1048576", "hw:numa_nodes": "1", "info:cpu:name": "Intel Cascade Lake 2.6GHz", "quota:conn_limit_total": "2000000", "quota:disk_max_num": "60", "quota:max_pps": "100000", "quota:max_rate": "800", "quota:min_rate": "150", "quota:physics_max_rate": "33000", "quota:scsi_disk_max_num": "60", "quota:vbd_disk_max_num": "24", "quota:vif_max_num": "2", "quota:vif_multiqueue_num": "1", "resource_type": "IOoptimizedS3"}, "original_name": "s3.medium.1", "ram": 1024, "swap": 0, "vcpus": 1}, "has_config_drive": false, "host": "878bbc505aea6b7ee410bef50cb622e603e8fd351d48dc3fc98575f7", "hostId": "878bbc505aea6b7ee410bef50cb622e603e8fd351d48dc3fc98575f7", "host_id": "878bbc505aea6b7ee410bef50cb622e603e8fd351d48dc3fc98575f7", "host_status": "UP", "hostname": "testhost", "hypervisor_hostname": "ac8ff6a8e9d01e1aa5cd26b49ebaa128131c87fde9db0622dbadfad8", "id": "71348e0b-55c9-42b4-b165-3256b007a674", "image": {"id": "48b793fc-7951-4e38-8bd7-7807cb9932f9"}, "instance_name": "instance-010d18ca", "interface_ip": "", "kernel_id": "", "key_name": "Ansiblemaster", "launch_index": 0, "launched_at": null, "location": {"cloud": "repository-dev", "project": {"domain_id": null, "domain_name": null, "id": "807609d5687e4592823fc5863c3ec484", "name": "eu-de_repository_dev"}, "region_name": "eu-de", "zone": "eu-de-01"}, "locked": false, "max_count": null, "metadata": {}, "min_count": null, "name": "testhost", "networks": {}, "os-extended-volumes:volumes_attached": [{"delete_on_termination": true, "id": "adb67f27-5d35-4b7d-ab44-40575ebb9dcd"}], "personality": null, "power_state": 0, "private_v4": "", "progress": 0, "project_id": "807609d5687e4592823fc5863c3ec484", "properties": {"OS-DCF:diskConfig": "MANUAL", "OS-EXT-AZ:availability_zone": "eu-de-01", "OS-EXT-SRV-ATTR:host": "878bbc505aea6b7ee410bef50cb622e603e8fd351d48dc3fc98575f7", "OS-EXT-SRV-ATTR:hostname": "testhost", "OS-EXT-SRV-ATTR:hypervisor_hostname": "ac8ff6a8e9d01e1aa5cd26b49ebaa128131c87fde9db0622dbadfad8", "OS-EXT-SRV-ATTR:instance_name": "instance-010d18ca", "OS-EXT-SRV-ATTR:kernel_id": "", "OS-EXT-SRV-ATTR:launch_index": 0, "OS-EXT-SRV-ATTR:ramdisk_id": "", "OS-EXT-SRV-ATTR:reservation_id": "r-qkyu60xj", "OS-EXT-SRV-ATTR:root_device_name": "/dev/vda", "OS-EXT-SRV-ATTR:user_data": null, "OS-EXT-STS:power_state": 0, "OS-EXT-STS:task_state": null, "OS-EXT-STS:vm_state": "error", "OS-SCH-HNT:scheduler_hints": null, "OS-SRV-USG:launched_at": null, "OS-SRV-USG:terminated_at": null, "host_status": "UP", "locked": false, "max_count": null, "min_count": null, "os-extended-volumes:volumes_attached": [{"delete_on_termination": true, "id": "adb67f27-5d35-4b7d-ab44-40575ebb9dcd"}], "trusted_image_certificates": null}, "public_v4": "", "public_v6": "", "ramdisk_id": "", "region": "eu-de", "reservation_id": "r-qkyu60xj", "root_device_name": "/dev/vda", "scheduler_hints": null, "security_groups": [], "server_groups": null, "status": "ERROR", "tags": [], "task_state": null, "tenant_id": "807609d5687e4592823fc5863c3ec484", "terminated_at": null, "trusted_image_certificates": null, "updated": "2022-02-02T13:26:47Z", "user_data": null, "user_id": "56a9d24620304da58503e29c9f0efd85", "vm_state": "error", "volumes": [{"delete_on_termination": true, "id": "adb67f27-5d35-4b7d-ab44-40575ebb9dcd"}]}}, "details": "None", "response": "None"}, "msg": "Error in creating the server (no further information available)"}
```

**Comment by outcatcher** [comment]
Can you please provide the playbook you've used to create this instance?

**Comment by wuebbels** [comment]
Sure, here is the playbook:
```
- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  vars:
    cloud: "{{ lookup('env', 'OS_CLOUD') }}"
    flavor: s3.medium.1
    az: eu-de-01
  tasks:
    - name: create primary nic port
      os_port:
        cloud: "{{ cloud }}"
        state: present
        name: "testhost-primarynic"
        allowed_address_pairs:
          - ip_address: "1.1.1.1/0"
        network: "repository"
        security_groups: ['sg-prometheus']
        fixed_ips:
          - ip_address: 172.16.57.5

    - name: create boot volume
      os_volume:
        cloud: "{{ cloud }}"
        state: present
        image: Debian_10_amd64-cloud-lvm_latest
        display_name: testhost
        availability_zone: "{{ az }}"
        size: 12

    - name: create server
      os_server:
        cloud: "{{ cloud }}"
        state: present
        name: testhost
        availability_zone: "{{ az }}"
        boot_volume: testhost
        key_name: Ansiblemaster
        flavor: "{{ flavor }}"
        security_groups: ['sg-prometheus']
        nics:
          - port-name: "testhost-primarynic"
        auto_ip: no
        terminate_volume: yes
```

**Comment by gtema** [comment]
@wuebbels , sure it is working with older sdk? Cause I experience similar issue not related to sdk

**Comment by wuebbels** [comment]
With ansible-4.10.0, openstacksdk-0.17.2 it also fails:
```
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": {"data": {"server": {"OS-DCF:diskConfig": "MANUAL", "OS-EXT-AZ:availability_zone": "eu-de-01", "OS-EXT-SRV-ATTR:host": "6aba703bbc2728b55b0030d3884eed39d151ba1c66be9a2825d4f9b9", "OS-EXT-SRV-ATTR:hypervisor_hostname": "946221f11546b7422b99e9648cb4f8005fe74471f6cb4d847b2d29d8", "OS-EXT-SRV-ATTR:instance_name": "instance-010d1b4f", "OS-EXT-STS:power_state": 0, "OS-EXT-STS:task_state": null, "OS-EXT-STS:vm_state": "error", "OS-SRV-USG:launched_at": null, "OS-SRV-USG:terminated_at": null, "accessIPv4": "", "accessIPv6": "", "addresses": {}, "adminPass": null, "az": "eu-de-01", "cloud": "repository-dev", "config_drive": "", "created": "2022-02-02T14:26:33Z", "created_at": "2022-02-02T14:26:33Z", "disk_config": "MANUAL", "fault": {"code": 500, "created": "2022-02-02T14:26:50Z", "message": "retry 2 times: Build of instance 8536ed70-5487-48b7-9410-828f0def0ab2 was re-scheduled: Proxy get error from cascaded nova api, reschedule.;Build of instance 8536ed70-5487-48b7-9410-828f0def0a.No valid host was found. There are not enough hosts available."}, "flavor": {"id": "s3.medium.1"}, "has_config_drive": false, "hostId": "6aba703bbc2728b55b0030d3884eed39d151ba1c66be9a2825d4f9b9", "host_id": "6aba703bbc2728b55b0030d3884eed39d151ba1c66be9a2825d4f9b9", "id": "8536ed70-5487-48b7-9410-828f0def0ab2", "image": {"id": "48b793fc-7951-4e38-8bd7-7807cb9932f9"}, "interface_ip": "", "key_name": "Ansiblemaster", "launched_at": null, "location": {"cloud": "repository-dev", "project": {"domain_id": null, "domain_name": null, "id": "807609d5687e4592823fc5863c3ec484", "name": "eu-de_repository_dev"}, "region_name": "eu-de", "zone": "eu-de-01"}, "metadata": {}, "name": "testhost", "networks": {}, "os-extended-volumes:volumes_attached": [{"id": "56bf6157-7f55-4d1d-9ac3-b3b6ccfc494c"}], "power_state": 0, "private_v4": "", "progress": 0, "project_id": "807609d5687e4592823fc5863c3ec484", "properties": {"OS-DCF:diskConfig": "MANUAL", "OS-EXT-AZ:availability_zone": "eu-de-01", "OS-EXT-SRV-ATTR:host": "6aba703bbc2728b55b0030d3884eed39d151ba1c66be9a2825d4f9b9", "OS-EXT-SRV-ATTR:hypervisor_hostname": "946221f11546b7422b99e9648cb4f8005fe74471f6cb4d847b2d29d8", "OS-EXT-SRV-ATTR:instance_name": "instance-010d1b4f", "OS-EXT-STS:power_state": 0, "OS-EXT-STS:task_state": null, "OS-EXT-STS:vm_state": "error", "OS-SRV-USG:launched_at": null, "OS-SRV-USG:terminated_at": null, "fault": {"code": 500, "created": "2022-02-02T14:26:50Z", "message": "retry 2 times: Build of instance 8536ed70-5487-48b7-9410-828f0def0ab2 was re-scheduled: Proxy get error from cascaded nova api, reschedule.;Build of instance 8536ed70-5487-48b7-9410-828f0def0a.No valid host was found. There are not enough hosts available."}, "os-extended-volumes:volumes_attached": [{"id": "56bf6157-7f55-4d1d-9ac3-b3b6ccfc494c"}]}, "public_v4": "", "public_v6": "", "region": "eu-de", "security_groups": [], "status": "ERROR", "task_state": null, "tenant_id": "807609d5687e4592823fc5863c3ec484", "terminated_at": null, "updated": "2022-02-02T14:26:50Z", "user_id": "56a9d24620304da58503e29c9f0efd85", "vm_state": "error", "volumes": [{"id": "56bf6157-7f55-4d1d-9ac3-b3b6ccfc494c"}]}}, "details": "None", "response": "None"}, "msg": "Error in creating the server: retry 2 times: Build of instance 8536ed70-5487-48b7-9410-828f0def0ab2 was re-scheduled: Proxy get error from cascaded nova api, reschedule.;Build of instance 8536ed70-5487-48b7-9410-828f0def0a.No valid host was found. There are not enough hosts available."}
```

With ansible-2.9.0, openstacksdk-0.61.0 it works. However, as I understand it, Ansible 2.9 will be end of life soon.

**Comment by enrrou** [comment]
@wuebbels, try to add bootable: true parameter to boot volume task, like that:
```
- name: create boot volume
   openstack.cloud.volume:
     state: present
     image: Standard_Debian_10_latest
     display_name: testhost
     availability_zone: "{{ az }}"
     bootable: yes
     size: 12
```
Works on openstacksdk-0.61.0 and ansible-4.1.0 also as on previous versions.
