### ISSUE TITLE
opentelekomcloud.cloud.cbr_vault  assign policy ends  with changed in the second and further run

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#227]
Hi all,

today i tried opentelekomcloud.cloud.cbr_vault.
After creating a server vault i  tried to bind a policy.

I i run the task several times it alway ends with changed. In my opionion only in the first run the task should end with changed.
Afterwards it should end with OK.

```
        - name: Associate policy
          opentelekomcloud.cloud.cbr_vault:
            name: "vault-gateway-server"
            resources:
              - id: '42604a31-d6dc-450b-9a06-3e4781da1ad8'
                type: "OS::Nova::Server"
              - id: '8d4d223a-1983-4f16-b13e-66726d6d036d'
                type: "OS::Nova::Server"
            action: "bind_policy"
            policy: "uli_policy"
```
Could you please check ?

Thanks in advance

Uli
