### ISSUE TITLE
Howto Create shared scsi volume

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#230]
Hi all,

i would like to create a shared scsi volume on OTC.

I am using ansible module

- openstack.cloud.volume

I am able to create a scsi volume by setting

- metadata: {"hw:passthrough": "true"}

But this volume should also be shareable among several hosts.   How can i configure this?

Thanks in advance

Uli

**Comment by hadoopch** [comment]
Hi all,

i was able to create a shared scsi volume by using the huawei ansible modules:

community.general.hwc_evs_disk

Regards

Uli

**Comment by Polina-Gubina** [comment]
Hi! could you clarify if you set 'multiattach' parameter to true or not?

**Comment by hadoopch** [comment]
Hi Polina, 

my goal is to create three shareable SCSI devices and attach them to two servers.  
First i tried to create the shareable volumes by using the standard openstack module:

- openstack.cloud.volume

Here i set metadata to {"hw:passthrough": "true"}. 

By using metadata i was able to create a scsci device but this volume was not shareable.
So i tried to set further key value pairs in metadata:
 "shareable"  : "True" or "multiattach": "True" but without success. 
Finally i was not able to get a shareable volume when i used:

- openstack.cloud.volume

So i had the idea to use the HWC modules which are part of the collection:

- community.general 

I tried the following module:

- community.general.hwc_evs_disk


With the following playbook i was able to create shared scsi volumes:

```
  tasks:
        - name: "Create shared scsi volume"
          community.general.hwc_evs_disk:
            state: "present"
            availability_zone: "eu-ch2a"
            name: 'my-shared-volume-01'
            size: "10"
            volume_type: "SAS"
            enable_scsi: "true"
            enable_share: "true"
```
You can see this module has to distinguished parameter for creating evs volumes:

- enable scsi 
- enable_share



The other parameter were provided by using environment variables, e.g.


```
export ANSIBLE_HWC_PROJECT=eu-ch2_dvs
export ANSIBLE_HWC_USER=A12650921
...
```` 


After that i tried to attach the volumes. You can see that the volume has the appropriate attributes:

```



{
  "attachments": [
    {
      "id": "21b5114d-7f39-4590-99bd-0c94222f7d11",
      "attachment_id": "e583bbfb-bc6a-4fb1-a0b8-5a1c276ba8bf",
      "volume_id": "21b5114d-7f39-4590-99bd-0c94222f7d11",
      "server_id": "30257b1c-29c5-46f9-87c5-186ca673705d",
      "host_name": null,
      "device": "/dev/sdd",
      "attached_at": "2022-11-07T14:12:43.989645"
    }
  ],
  "availability_zone": "eu-ch2b",
  "bootable": "false",
  "consistencygroup_id": null,
  "created_at": "2022-11-07T13:52:37.152961",
  "description": null,
  "encrypted": false,
  "id": "21b5114d-7f39-4590-99bd-0c94222f7d11",
  "multiattach": true,
  "name": "kunde1-sbdfence-03",
  "os-vol-host-attr:host": "cinder-kvm002@SAS#0",
  "os-vol-mig-status-attr:migstat": null,
  "os-vol-mig-status-attr:name_id": null,
  "os-vol-tenant-attr:tenant_id": "6573b4be93e742f9a45b0f2d33e6b03b",
  "os-volume-replication:extended_status": null,
  "properties": {
    "hw:passthrough": "true",
    "readonly": "False"
  },
  "replication_status": "disabled",
  "shareable": true,
  "size": 10,
  "snapshot_id": null,
  "source_volid": null,
  "status": "in-use",
  "type": "SAS",
  "updated_at": "2022-11-07T14:24:47.775719",
  "user_id": "1fe0961c3a7a434ca026ff726b4656d2",
  "volume_image_metadata": {}
}
```

Fo attaching the volume i Used 

-   openstack.cloud.server_volume:

Here is the playbook.  

```
- name: "Volume Attachment  {{svol.size}} GByte {{svol.volume_type}} {{svol.name}} to ECS instance"
  openstack.cloud.server_volume:
   state: "{{_action}}"
   server: "{{item.0}}"
   volume: "{{item.1}}"
  tags:
   - SVOL
  when: _action == "present"
  ignore_errors: yes
  with_nested:
   - "{{ svol.serverlist}}"
   - "{{svol.devicelist}}"

```

The attachment to the secomnd server always failed  and i got an 'in use' error.


Thanks for your support.


Regards

Uli
