### ISSUE TITLE
Example in doc of  opentelekomcloud.cloud.vpc_peering is wrong

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#258]
Hello ,

today i used opentelekomcloud.cloud.vpc_peering  module.

I checked the example in the doc:

```
# Create a vpc peering.
- opentelekomcloud.cloud.vpc_peering:
    name: "peering1"
    local_router: "local-router"
    local_project_id: "959db9b6017d4a1fa1c6fd17b6820f55"
    remote_router: "peer-router"
    remote_project_id: "959db9b6017d4a1fa1c6fd17b6820f55"
```

According to the the example the options for the local and the remote project ID are:

- local_project_id
- remote_project_id

But this is not working.  The options are:

- local_project
- remote_project

It would be very helpful if you could correct the doc.

Thanks in advance

Uli
