### ISSUE TITLE
opentelekomcloud.cloud.vpc_peering is not working with router names

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#259]
Hello,

according to the doc the module should work with router names (local and remote):

```
- local_router
        Name or ID of the local router.
        [Default: (null)]
        type: str
```

Also in the example a router name is used
```
- opentelekomcloud.cloud.vpc_peering:
    name: "peering1"
    local_router: "local-router"
    local_project_id: "959db9b6017d4a1fa1c6fd17b6820f55"
    remote_router: "peer-router"
    remote_project_id: "959db9b6017d4a1fa1c6fd17b6820f55"
``` 

But if you use a router  name you get the following error:

```
    },
    "msg": "Invalid input for accept_vpc_info. Reason: 'kunde1-VPC' is not a valid UUID.: Client Error for url: https://vpc.eu-ch2.sc.otc.t-systems.com/v2.0/vpc/peerings, Invalid input for accept_vpc_info. Reason: 'kunde1-VPC' is not a valid UUID."
}
```

Regards

Uli
