### ISSUE TITLE
Example in doc of opentelekomcloud.cloud.vpc_route is wrong

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#260]
Hello ,

today i used opentelekomcloud.cloud.vpc_route module.

I checked the example in the doc:

```
# Create a vpc route.
- opentelekomcloud.cloud.vpc_route:
    destination: "6ysa5bac-0925-6d5b-add8-cb6667b8"
    nexthop: "67sa5bac-0925-4p5b-add8-cb6667b8"
    router_id: "89sa5bac-0925-9h7b-add8-cb6667b8"
  register: vpc_route

```
According to the example the option for the router ID is:

- router_id

But this is not working. The options is:

- router

Could you please correct the doc?

Thanks in advance

This is also confusing:

```
- router
        ID or name of the router requesting for creating a route.
        [Default: (null)]
        type: str
```

Because names are not working.

Regards

Uli

**Comment by hadoopch** [comment]
Hi ,

the delete example seems to be wrong too.

```
# Delete vpc route
- opentelekomcloud.cloud.vpc_route:
    name: "peering2"
    state: absent
```

There is no option **name** available.  

A woprking  example would be:

```
- name: "Delete Route"
  opentelekomcloud.cloud.vpc_route:
     route_id: a5904bd2-9b35-4957-8705-0ad5ab95a77b
     state: absent

```
Regards
Uli
