### ISSUE TITLE
dns_zone module

### ISSUE THREAD

**Issue by flwitten** [opentelekomcloud/ansible-collection-cloud#335]
Hi everyone,

If I'm running e.g.

```yaml
- name: Create private zones
  opentelekomcloud.cloud.dns_zone:
    name:        "example.com."
    state:       present
    zone_type:   private
    router:      "{{ vpc_info.vpc.id }}"
    description: Test Private Zone
    ttl:         300
    email:       root@example.com
```
The DNS-Privatezone is created. That works, but If I run the playbook again it's not returning an OK as expected but an error.

```
fatal: [localhost]: FAILED! => 
{
	"changed": false,
	"extra_data": 
		{
			"data": null, 
			"details": "This VPC has already been associated with the zone. Zone ID:******************.", 
			"response": "{\"code\":\"DNS.0212\",\
			"message\":\"This VPC has already been associated with the zone. Zone ID:*******************.\"}"}, 
			"msg": "This VPC has already been associated with the zone. Zone ID:************.: Client Error for url: https://dns.eu-de.otc.t-systems.com/v2/zones, This VPC has already been associated with the zone. Zone ID:***************."}
```

Is this the expected behaviour?

Thank you in advance,
Best regards
