### ISSUE TITLE
dns_zone issue with wrong response

### ISSUE THREAD

**Issue by tischrei** [opentelekomcloud/ansible-collection-cloud#358]
Creating a zone with wrong vpc-name results in wrong output. The playbook is not aborting, instead it runs through:

sample play:

```
- hosts: localhost
  tasks: 
    - name: Create private zone
      opentelekomcloud.cloud.dns_zone:
        cloud: otc
        name: tinozone2
        state: present
        zone_type: "private"
        router: "vpc-tino"
      register: zone
```

```
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_timeout": null,
            "auth": null,
            "auth_type": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "description": null,
            "email": null,
            "interface": "public",
            "name": "tinozone2",
            "region_name": null,
            "router": "vpc-tino",
            "sdk_log_level": "WARN",
            "sdk_log_path": null,
            "state": "present",
            "timeout": 180,
            "ttl": null,
            "validate_certs": null,
            "wait": true,
            "zone_type": "private"
        }
    },
    "message": "No Router found with name or id: vpc-tino"
}


```
