### ISSUE TITLE
Not Able to Create Port with Openstack to assign Fixed IP

### ISSUE THREAD

**Issue by sunilmore690** [opentelekomcloud/ansible-collection-cloud#360]
As I need to create port for  Private IP using following snippet 

```
- name: "Creating port for Private IP {{private_ip_1}}"
  openstack.cloud.port:
    state: present
    auth: "{{otc_auth}}"
    name: "{{port_name}}”
    network: "{{network_name}}"
    fixed_ips:
      - ip_address: "{{private_ip_1}}"
  register: private_ip_port_res
```
But getting below Issue 

"ResourceNotFound: 404: Client Error for url: https://vpc.eu-de.otc.t-systems.com/v2.0/extensions, Not Found`
