### ISSUE TITLE
Not Able to Create Port with Openstack to assign Fixed IP (reopen)

### ISSUE THREAD

**Issue by spech66** [opentelekomcloud/ansible-collection-cloud#373]
> This is an internal issue with our API. We’ve shared a possible workaround via email, so I'll close this issue for now. 

 _Originally posted by @anton-sidelnikov in [#360](https://github.com/opentelekomcloud/ansible-collection-cloud/issues/360#issuecomment-2470050368)_

We are facing the same problem and would be glad to have a solution for this.

**Comment by spech66** [comment]
I tried to use the port but this Endpoint doesn't work either.

```yaml
    - name: Create port for internal IP
      openstack.cloud.port:
        name: "xxx-port"
        network: xxx
        fixed_ips:
          - ip_address: "192.168.10.10"
        state: present
    - name: Attach port to server
      openstack.cloud.server:
        name: "xxx"
        state: present
        nics:
          - port-name: "xxx-port"
```

**Comment by spech66** [comment]
Anyone who stumbles across it. Here is a solution

```yaml
    - name: Get subnets
      opentelekomcloud.cloud.subnet_info:
      register: subnet_info
    - name: Create server
      openstack.cloud.server:
        # [--nic <net-id=net-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid,auto,none>] # https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/server.html
        nics: 
          - net-id: "{{ subnet_info.subnets | selectattr('name', 'match', item.value.subnet_name) | map(attribute='id') | first }}"
            v4-fixed-ip: "{{ item.value.ecs_ipaddress }}"
```
