### ISSUE TITLE
Disk encryption on ECS

### ISSUE THREAD

**Issue by spech66** [opentelekomcloud/ansible-collection-cloud#375]
Is there any way to set `disk_encryption` for ECS like the RDS role? Neither `openstack.cloud.volume` nor `openstack.cloud.server` and there is no dedicated OTC role as far as I know.

**Comment by spech66** [comment]
Anyone who stumbles across it. Here is a solution

```yaml
    - name: Create volume for server
      openstack.cloud.volume:
        name: "{{ item.key }}-volume"
        size: "{{ item.value.ecs_volumesize | default(default.otc_ecs_volumesize) }}"
        image: "{{ default.otc_ecs_image_name }}"
        volume_type: "{{ item.value.ecs_volumetype | default(default.otc_ecs_volumetype) }}"
        availability_zone: "{{ default.otc_availability_zone }}"
        metadata:
          __system__encrypted: "{{ '1' if item.value.ecs_volume_encryption_cmkid | default(default.otc_ecs_volume_encryption_cmkid) else '0' }}"
          __system__cmkid: "{{ item.value.ecs_volume_encryption_cmkid | default(default.otc_ecs_volume_encryption_cmkid) }}"
      loop: "{{ vms | dict2items }}"
    - name: Get volumes
      openstack.cloud.volume_info:
      register: volumes
    - name: Create server
      openstack.cloud.server:
        name: "{{ item.key }}"
        availability_zone: "{{ default.otc_availability_zone }}"
        flavor: "{{ item.value.ecs_flavor | default(default.otc_ecs_flavor) }}"
        key_name: "{{ default.otc_keypair_adminkey }}"
        security_groups: "{{ item.value.secgroups | default(default.otc_sg_default) }}"
        auto_ip: false
        boot_volume: "{{ volumes.volumes | selectattr('name', 'match', item.key ~ '-volume') | map(attribute='id') | first }}"
        # [--nic <net-id=net-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid,auto,none>] # https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/server.html
        nics: 
          - net-id: "{{ subnet_info.subnets | selectattr('name', 'match', item.value.subnet_name) | map(attribute='id') | first }}"
            v4-fixed-ip: "{{ item.value.ecs_ipaddress }}"
        tags: # Without this the ansible module throws an error...
        state: present
```
